version: '3.9'
services:
  node-debug:
    build:
      context: .
      dockerfile: ./Dockerfile.debug
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
