version: '3.9'
services:
  node-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
